[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "invest-schistosomiasis"
dynamic = ["version"]
dependencies = [
  "pygeoprocessing",
  "taskgraph",
  "natcap.invest>=3.20.0",
  "geojson",
  "gdal-utils"
]

[tools.setuptools_scm]

[tool.natcap.invest]
api_version = "v1"
package_name = "invest_schistosomiasis"
conda_dependencies = [
	"python==3.13",
	"gdal!=3.11",
	"geotiff>=1.7.3",
	"pygeoprocessing",
	"natcap.invest>=3.20.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
# Use this to include any non-python files in your package distribution,
# such as data required by your package, or a non-python executable
